### ISSUE TITLE
Add rust language support

### ISSUE THREAD

**Issue by Gozala** [MaxGraey/Assembleash#8]

**Comment by MaxGraey** [comment]
Sorry, but Rust is compiled language without asm.js or wasm compiler which can run in client browser as I know so in this case we need backend with rust compiler which quite completed in current time. Another misalignment is **Assembleah** focused strongly to typescript-like languages and all ecosystem tuned for that.

**PS** And Rust already have some [playground](https://play.rust-lang.org/)

**Comment by MaxGraey** [comment]
Rust now support in [WebAssembly Studio](https://webassembly.studio/)
